export const ENV_KEYS = {
  JENKINS_URL: "JENKINS_URL",
  JENKINS_USER: "JENKINS_USER",
  JENKINS_API_TOKEN: "JENKINS_API_TOKEN",
  JENKINS_BRANCH_PARAM: "JENKINS_BRANCH_PARAM",
  JENKINS_USE_CRUMB: "JENKINS_USE_CRUMB",
  JENKINS_DEBUG: "JENKINS_DEBUG",
  JENKINS_CLI_CONFIG_DIR: "JENKINS_CLI_CONFIG_DIR",
} as const;
