/**
 * Error codes and process exit codes. Both are part of the public contract:
 * `--json` errors carry the error code, and the exit code is derived from it,
 * so scripts can branch on either without parsing text. The README documents
 * the exit code table; keep the two in sync.
 */
import { CliError } from "./cli";

export const EXIT_CODES = {
  SUCCESS: 0,
  /** The build or operation finished unsuccessfully, or an unclassified error. */
  FAILURE: 1,
  USAGE: 2,
  AUTH: 3,
  NOT_FOUND: 4,
  PROTECTED_PROFILE: 5,
  /** Jenkins could not be reached, timed out, or answered with an error. */
  JENKINS: 6,
  TIMEOUT: 124,
  INTERRUPTED: 130,
} as const;

export type ExitCode = (typeof EXIT_CODES)[keyof typeof EXIT_CODES];

const ERROR_EXIT_CODES = {
  INVALID_USAGE: EXIT_CODES.USAGE,
  INVALID_BUILD_NUMBER: EXIT_CODES.USAGE,
  INVALID_BUILD_SELECTOR: EXIT_CODES.USAGE,
  INVALID_LIMIT: EXIT_CODES.USAGE,
  INVALID_LOG_SELECTOR: EXIT_CODES.USAGE,
  AMBIGUOUS_STAGE_SELECTOR: EXIT_CODES.USAGE,
  CROSS_CONTROLLER_URL: EXIT_CODES.USAGE,
  JOB_AMBIGUOUS: EXIT_CODES.USAGE,
  INPUT_ACTION_AMBIGUOUS: EXIT_CODES.USAGE,
  INPUT_CONFIRMATION_REQUIRED: EXIT_CODES.USAGE,
  CONFIG_INVALID: EXIT_CODES.USAGE,
  /** HTTP 400: Jenkins refused the request as sent, e.g. an invalid parameter value. */
  JENKINS_BAD_REQUEST: EXIT_CODES.USAGE,

  CREDENTIALS_MISSING: EXIT_CODES.AUTH,
  JENKINS_AUTH_ERROR: EXIT_CODES.AUTH,
  JENKINS_LOGIN_REDIRECT: EXIT_CODES.AUTH,
  JENKINS_CRUMB_REJECTED: EXIT_CODES.AUTH,
  INPUT_PERMISSION_DENIED: EXIT_CODES.AUTH,
  TEST_REPORT_PERMISSION_DENIED: EXIT_CODES.AUTH,

  JENKINS_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  JOB_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  JOB_CACHE_EMPTY: EXIT_CODES.NOT_FOUND,
  BUILD_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  NO_BUILDS: EXIT_CODES.NOT_FOUND,
  NO_COMPLETED_BUILD: EXIT_CODES.NOT_FOUND,
  NO_ACTIVE_BUILD: EXIT_CODES.NOT_FOUND,
  QUEUE_ITEM_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  PIPELINE_STAGE_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  FAILED_STAGE_UNAVAILABLE: EXIT_CODES.NOT_FOUND,
  INPUT_NOT_PENDING: EXIT_CODES.NOT_FOUND,
  INPUT_ACTION_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  INPUT_ACTION_STALE: EXIT_CODES.NOT_FOUND,
  TEST_REPORT_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  ARTIFACT_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  PROFILE_NOT_FOUND: EXIT_CODES.NOT_FOUND,

  PROFILE_PROTECTED: EXIT_CODES.PROTECTED_PROFILE,

  JENKINS_UNREACHABLE: EXIT_CODES.JENKINS,
  JENKINS_TIMEOUT: EXIT_CODES.JENKINS,
  JENKINS_HTTP_ERROR: EXIT_CODES.JENKINS,
  JENKINS_INVALID_RESPONSE: EXIT_CODES.JENKINS,
  PIPELINE_INPUT_INVALID_RESPONSE: EXIT_CODES.JENKINS,
  PIPELINE_INPUT_UNSUPPORTED: EXIT_CODES.JENKINS,
  PIPELINE_STAGE_LOG_UNAVAILABLE: EXIT_CODES.JENKINS,
  INPUT_ACTION_URL_INVALID: EXIT_CODES.JENKINS,
  INPUT_SUBMISSION_REJECTED: EXIT_CODES.JENKINS,
  INPUT_OUTCOME_UNKNOWN: EXIT_CODES.JENKINS,
  INPUT_PARAMETERS_UNKNOWN: EXIT_CODES.JENKINS,
  TEST_REPORT_TRANSPORT_ERROR: EXIT_CODES.JENKINS,
  TEST_REPORT_MALFORMED: EXIT_CODES.JENKINS,
  TEST_REPORT_UNAVAILABLE: EXIT_CODES.JENKINS,
  CHANGES_MALFORMED: EXIT_CODES.JENKINS,
  TIMESTAMP_METADATA_UNAVAILABLE: EXIT_CODES.JENKINS,

  INPUT_PARAMETERS_UNSUPPORTED: EXIT_CODES.FAILURE,
  CANCEL_INCOMPLETE: EXIT_CODES.FAILURE,
  CONFIG_WRITE_FAILED: EXIT_CODES.FAILURE,
  SECURE_STORE_ERROR: EXIT_CODES.FAILURE,
  ARTIFACT_PATH_UNSAFE: EXIT_CODES.FAILURE,
  BROWSER_FAILED: EXIT_CODES.FAILURE,
  UPDATE_FAILED: EXIT_CODES.FAILURE,
  VERSION_UNSUPPORTED: EXIT_CODES.FAILURE,
  UNEXPECTED_ERROR: EXIT_CODES.FAILURE,

  OPERATION_CANCELLED: EXIT_CODES.INTERRUPTED,
} as const satisfies Record<string, ExitCode>;

export type ErrorCode = keyof typeof ERROR_EXIT_CODES;

export function exitCodeFor(error: unknown): ExitCode {
  return error instanceof CliError
    ? ERROR_EXIT_CODES[error.code]
    : EXIT_CODES.FAILURE;
}
